name: getx_skeleton
version: 3.0.0+13
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.16.0 <3.0.0'

#
dependencies:
  cupertino_icons:
  get: # for state managment and context less stuff
  permission_handler: ^10.2.0
  logger: # log events in clear way insted of (print)

  flutter_screenutil: # make app responsive

  dio: # for api requests

  hive:  # local database (SQFlite replacement)
  hive_flutter: # make it easy to use hive (no need for path provider)
  get_storage: # shared preferences replacement (sync)

  firebase_core: ^2.8.0
  firebase_analytics:
  firebase_auth: ^4.9.0
  cloud_firestore:
  firebase_dynamic_links:
  firebase_messaging:
  firebase_storage:
  awesome_notifications: ^0.7.4+1 # notifications services (will be used for fcm) # change app icon
  change_app_package_name: # change package name
  rename_app: # rename app

  cached_network_image: # image caching
  flutter_svg: ^1.0.3 # for svg images
  roundcheckbox:
  image_picker:
  google_maps_flutter: ^2.3.0
  flutter_polyline_points: ^1.0.0
  flutter_native_image: # for compressing images.
  jiffy: # for time formatting
  easy_refresh: # refresh lists and fetch data from server
  #flutter_stripe: # for payments

  webview_flutter:
  intl_phone_field:
  font_awesome_flutter:
  lottie:
  sliding_switch:
  flutter_cupertino_datetime_picker:
  location: ^5.0.0
  flutter_automation: ^2.0.0
  timer_count_down: ^2.2.1
  simple_star_rating: ^0.0.3
  url_launcher:
  fast_contacts: ^3.0.3
  sms_mms: ^0.0.2+1
  pay: ^1.0.11


  flutter:
    sdk: flutter
  #purchases_flutter: ^4.5.4
  google_fonts: ^4.0.3
  camera: ^0.10.2
  intl: ^0.18.1
  video_player: ^2.5.1
  path_provider: ^2.0.12
  path: ^1.8.1
  gallery_saver: ^2.3.2
  vibration: ^1.7.6
  table_calendar: ^3.0.8
  device_preview: ^1.1.0
  chewie: ^1.4.0
  flutter_countdown_timer: ^4.1.0
  country_picker: ^2.0.20
  fluttertoast: ^8.2.1
  image_cropper: ^3.0.2
  flutter_cache_manager: ^3.3.0
  custom_info_window: ^1.0.1


dev_dependencies:
  flutter_lints:
  build_runner:  # generate dart files
  hive_generator: # generate hive files
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter

dependency_overrides:
#  firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true



  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/icons/
    - assets/markers/
    - assets/svg_icons/
    - assets/lottie/
    - assets/json/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900